# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc
# copied from https://github.com/CLIUtils/CLI11

trigger:
- master

pr:
- master

variables:
  containers.std: 14
  containers.build_type: Debug
  containers.options: -DCONTAINERS_ENABLE_TESTS=ON -DCONTAINERS_ENABLE_ERROR_ON_WARNINGS=ON
  CMAKE_BUILD_PARALLEL_LEVEL: 4

jobs:

- job: ClangTidy
  variables:
    CXX_FLAGS: "-Werror -Wcast-align -Wfloat-equal -Wimplicit-atomic-properties -Wmissing-declarations -Woverlength-strings -Wshadow -Wstrict-selector-match -Wundeclared-selector -Wunreachable-code -std=c++11"
    containers.options: -DCONTAINERS_CLANG_TIDY=ON -DCONTAINERS_CLANG_TIDY_OPTIONS="-fix"
    containers.std: 14
    CMAKE_BUILD_PARALLEL_LEVEL: 1
  pool:
    vmImage: 'ubuntu-latest'
  container: silkeh/clang:8
  steps:
    - template: .ci/azure-cmake.yml
    - template: .ci/azure-build.yml
    - script: git diff --exit-code --color
      displayName: Check tidy

- job: CppLint
  variables:
    containers.options:
  pool:
    vmImage: 'ubuntu-latest'
  container: sharaku/cpplint:latest
  steps:
    - bash: cpplint --counting=detailed --recursive gmlc tests benchmarks --exclude optional.hpp
      displayName: Checking against google style guide

- job: Native
  strategy:
    matrix:
      Linux14:
        vmImage: 'ubuntu-latest'
      macOS17:
        vmImage: 'macOS-latest'
        containers.std: 17
      macOS11:
        vmImage: 'macOS-latest'
      Windows17:
        vmImage: 'vs2017-win2016'
        containers.std: 17
      Windows11:
        vmImage: 'vs2017-win2016'
      Windowslatest:
        vmImage: 'windows-2019'
        containers.std: 17
  pool:
    vmImage: $(vmImage)
  steps:
    - template: .ci/azure-build.yml
    - template: .ci/azure-test.yml

- job: Docker
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      gcc8:
        containerImage: gcc:8
        containers.std: 17
      clang3.6:
        containerImage: silkeh/clang:3.6
        containers.options: -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
      clang8:
        containerImage: helics/buildenv:clang8-builder
  container: $[ variables['containerImage'] ]
  steps:
    - template: .ci/azure-cmake.yml
    - template: .ci/azure-build.yml
    - template: .ci/azure-test.yml
